; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
build_flags = 
	-I include
	-I src/board
	-I src/ble
	-I src/domain
	-I src/peripherals
	-I src/server
lib_deps = 
	ottowinter/AsyncMqttClient-esphome@^0.8.6
	bblanchon/ArduinoJson@^7.4.2
	mandulaj/PZEM-004T-v30
